/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Button} from 'react-native';
import KeychainStore from 'react-native-keychain-store';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {
    // KeychainStore.sampleMethod('Testing', 123, message => {
    //   this.setState({
    //     status: 'native callback received',
    //     message,
    //   });
    // });
    KeychainStore.setItem('token', 'my_valuessssssqqq').then(message => {
      this.setState({
        status: 'SET ITEM',
        message,
      });
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆KeychainStore example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button
          title="Get"
          onPress={() => {
            console.log('Getting');
            KeychainStore.getItem('token').then(res => {
              console.log('GOT: ', res);
              this.setState({
                message: res,
              });
            });
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
